# k8s/monitoring/alerts.yaml

apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: app-alerts
  namespace: monitoring
  labels:
    release: monitoring
spec:
  groups:
  - name: app
    rules:
    # High Error Rate
    - alert: HighErrorRate
      expr: |
        sum(rate(http_server_requests_seconds_count{status=~"5.."}[5m])) 
        / 
        sum(rate(http_server_requests_seconds_count[5m])) 
        > 0.05
      for: 5m
      annotations:
        summary: "High error rate detected"
    
    # High Latency
    - alert: HighLatency
      expr: |
        histogram_quantile(0.95, 
          rate(http_server_requests_seconds_bucket[5m])
        ) > 0.3
      for: 5m
      annotations:
        summary: "API latency is high"
    
    # Pod Down
    - alert: PodDown
      expr: up == 0
      for: 2m
      annotations:
        summary: "Pod is down"