# k8s/monitoring/values.yaml

grafana:
  enabled: true
  adminPassword: "admin123" #اغيرها مممهههمممم
  service:
    type: LoadBalancer
  
  dashboards:
    default:
      kubernetes-cluster:
        gnetId: 7249
        datasource: Prometheus
      kubernetes-pods:
        gnetId: 6417
        datasource: Prometheus
      spring-boot:
        gnetId: 12900
        datasource: Prometheus
      nginx-ingress:
        gnetId: 9614
        datasource: Prometheus

prometheus:
  prometheusSpec:
    retention: 7d
    serviceMonitorSelectorNilUsesHelmValues: false

alertmanager:
  enabled: true