# k8s/monitoring/values.yaml

grafana:
  enabled: true
  adminPassword: "admin123"  # غيرها!
  service:
    type: LoadBalancer
  
  dashboards:
    default:
      kubernetes-cluster:
        gnetId: 7249
        datasource: Prometheus
      kubernetes-pods:
        gnetId: 6417
        datasource: Prometheus
      spring-boot:
        gnetId: 12900
        datasource: Prometheus
      nginx-ingress:
        gnetId: 9614
        datasource: Prometheus

prometheus:
  prometheusSpec:
    retention: 7d
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector: {}

alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m
      # Email configuration
      smtp_smarthost: 'smtp.gmail.com:587'
      smtp_from: 'lamanasser56@gmail.com'
      smtp_auth_username: 'lamanasser56@gmail.com'
      smtp_auth_password: 'your-app-password'
      smtp_require_tls: true
    
    route:
      group_by: ['alertname', 'namespace', 'severity']
      group_wait: 10s
      group_interval: 10s
      repeat_interval: 12h
      receiver: 'default'
      
      routes:
      - match:
          severity: critical
        receiver: 'critical-alerts'
        continue: true
      - match:
          severity: warning
        receiver: 'warning-alerts'
    
    receivers:
    - name: 'default'
      email_configs:
      - to: 'team@example.com'
        send_resolved: true
    
    - name: 'critical-alerts'
      email_configs:
      - to: 'oncall@example.com'
        send_resolved: true
        headers:
          Subject: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
    
    - name: 'warning-alerts'
      email_configs:
      - to: 'team@example.com'
        send_resolved: true
        headers:
          Subject: '⚠️ WARNING: {{ .GroupLabels.alertname }}'