apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: grp1-app
type: Opaque
stringData:
  DB_HOST: "grp1-sqlsrv.database.windows.net"
  DB_NAME: "grp1-sqldb"
  DB_USERNAME: "adminuser"
  DB_PASSWORD: "StrongPassword123!"
  DB_PORT: "1433"
