apiVersion: v1
kind: Service
metadata:
  name: app-backend-service
  namespace: app
spec:
  selector:
    app: backend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
