apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: backend-alerts
  namespace: monitoring
spec:
  groups:
  - name: backend.rules
    rules:
    - alert: HighBackendErrorRate
      expr: |
        sum by (job) (rate(http_server_requests_seconds_count{job="backend",status=~"5.."}[5m])) 
        /
        sum by (job) (rate(http_server_requests_seconds_count{job="backend"}[5m])) 
        > 0.05
      for: 5m
      labels:
        severity: page
      annotations:
        summary: "Backend 5xx error rate > 5%"
        description: "تحقق من الـ backend logs والـ deployments الأخيرة"

    - alert: HighLatencyP95
      expr: histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket{job="backend"}[5m])) by (le))
      > 0.3
      for: 5m
      labels:
        severity: ticket
      annotations:
        summary: "Backend p95 latency > 300ms"
        description: "تحقق من الـ backend performance/HPA"
