apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: backend-servicemonitor
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: backend
  endpoints:
    - port: http-metrics
      path: /actuator/prometheus
      interval: 15s
