prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    retention: "15d"
    resources:
      requests:
        cpu: "500m"
        memory: "1Gi"

grafana:
  enabled: true
  adminUser: "group1"
  adminPassword: "" # سيتم استخدام Key Vault + CSI
  persistence:
    enabled: true
    size: 10Gi
  additionalDataSources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-operated.monitoring.svc.cluster.local:9090
      isDefault: true

prometheusOperator:
  tlsProxy:
    enabled: false
