# .github/workflows/monitoring-stack.yml

name: Deploy Monitoring

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ secrets.AZURE_RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}
      
      - name: Install Helm
        run: |
          curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      
      - name: Deploy Monitoring Stack
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          
          helm upgrade --install monitoring prometheus-community/kube-prometheus-stack \
            --namespace monitoring \
            --create-namespace \
            --values k8s/monitoring/values.yaml \
            --wait
      
      - name: Apply ServiceMonitors
        run: |
          kubectl apply -f k8s/monitoring/backend-monitor.yaml
          kubectl apply -f k8s/monitoring/frontend-monitor.yaml
          kubectl apply -f k8s/monitoring/alerts.yaml
      
      - name: Get Grafana URL
        run: |
          kubectl get svc -n monitoring