name: "Build & Push Frontend (Vite)"

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  workflow_dispatch:

env:
  FE_IMAGE: "docker.io/aalhatlan/fe-final-project"

jobs:
  build_frontend:
    name: Build & Push Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Generate Version Tag
        id: version
        run: echo "frontend=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: DockerHub Login
        uses: docker/login-action@v3
        with:
          username: aalhatlan
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Resolve Backend URL
        id: backend_url
        shell: bash
        run: |
          set -euo pipefail
          url="${{ secrets.VITE_API_BASE_URL || secrets.BACKEND_URL || vars.VITE_API_BASE_URL || vars.BACKEND_URL || '' }}"
          if [ -z "$url" ]; then url="http://localhost:8080"; fi
          echo "backend_url=$url" >> "$GITHUB_OUTPUT"

      - name: Build & Push Frontend (Vite)
        run: |
          docker build --platform linux/amd64 \
            --build-arg VITE_API_BASE_URL=${{ steps.backend_url.outputs.backend_url }} \
            -t ${{ env.FE_IMAGE }}:${{ steps.version.outputs.frontend }} \
            -t ${{ env.FE_IMAGE }}:latest \
            -f frontend/Dockerfile .

          docker push ${{ env.FE_IMAGE }}:${{ steps.version.outputs.frontend }}
          docker push ${{ env.FE_IMAGE }}:latest
