name: Infra Deploy

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform
    env:
      TF_VAR_sql_password: ${{ secrets.SQL_ADMIN_PASSWORD }}
      TF_VAR_location: ${{ secrets.AZURE_LOCATION || vars.AZURE_LOCATION || 'eastus2' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.3

      - name: Terraform Init (with backend)
        run: terraform init -input=false

      - name: Cleanup legacy ACR state (best-effort)
        shell: bash
        run: |
          set -euo pipefail
          terraform state list | grep -q '^azurerm_role_assignment\.acr_pull$' && terraform state rm azurerm_role_assignment.acr_pull || true
          if terraform state list | grep -q '^module\.acr\.'; then
            terraform state list | awk '/^module\.acr\./{print $0}' | xargs -r -n1 terraform state rm || true
          fi

      - name: Terraform Apply
        run: terraform apply -auto-approve -lock=false -input=false

  k8s_apply:
    name: Kubernetes Apply
    runs-on: ubuntu-latest
    needs: terraform_apply
    env:
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG || vars.KUBE_CONFIG || '' }}
      KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA || vars.KUBE_CONFIG_DATA || '' }}
      K8S_NAMESPACE: ${{ secrets.K8S_NAMESPACE || vars.K8S_NAMESPACE || 'default' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect k8s manifests
        id: detect
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p k8s || true
          files=$(find k8s -type f \( -name '*.yml' -o -name '*.yaml' \) -size +0c | sort || true)
          if [ -n "$files" ]; then
            echo "found=true" >> "$GITHUB_OUTPUT"
            printf '%s\n' "$files" > manifest-list.txt
            echo "Manifests to apply:"; cat manifest-list.txt
          else
            echo "found=false" >> "$GITHUB_OUTPUT"
            echo "No non-empty k8s manifests found; skipping apply."
          fi

      - name: Setup kubectl
        if: steps.detect.outputs.found == 'true'
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.30.0'

      - name: Configure kubeconfig (direct)
        if: steps.detect.outputs.found == 'true' && env.KUBE_CONFIG != ''
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p ~/.kube
          printf "%s" "$KUBE_CONFIG" > ~/.kube/config
          chmod 600 ~/.kube/config
          kubectl config view --minify || true

      - name: Configure kubeconfig (base64)
        if: steps.detect.outputs.found == 'true' && env.KUBE_CONFIG == '' && env.KUBE_CONFIG_DATA != ''
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p ~/.kube
          printf "%s" "$KUBE_CONFIG_DATA" | base64 -d > ~/.kube/config
          chmod 600 ~/.kube/config
          kubectl config view --minify || true

      - name: Skip — no kubeconfig provided
        if: steps.detect.outputs.found == 'true' && env.KUBE_CONFIG == '' && env.KUBE_CONFIG_DATA == ''
        run: echo "No KUBE_CONFIG or KUBE_CONFIG_DATA provided; skipping kubectl apply." >> "$GITHUB_STEP_SUMMARY"

      - name: kubectl apply
        if: steps.detect.outputs.found == 'true' && (env.KUBE_CONFIG != '' || env.KUBE_CONFIG_DATA != '')
        shell: bash
        run: |
          set -euo pipefail
          if [ -f k8s/namespace.yml ] || [ -f k8s/namespace.yaml ]; then
            kubectl apply -f k8s/namespace.yml || kubectl apply -f k8s/namespace.yaml || true
          fi
          kubectl apply -R -f k8s
          printf "Applied manifests to namespace '%s'\n" "$K8S_NAMESPACE" >> "$GITHUB_STEP_SUMMARY"

      - name: Check rollout (best-effort)
        if: steps.detect.outputs.found == 'true' && (env.KUBE_CONFIG != '' || env.KUBE_CONFIG_DATA != '')
        continue-on-error: true
        shell: bash
        run: |
          set -euo pipefail
          echo "Checking deployment rollouts in namespace: $K8S_NAMESPACE"
          kubectl -n "$K8S_NAMESPACE" get deploy || exit 0
          kubectl -n "$K8S_NAMESPACE" rollout status deploy --timeout=120s
