name: Deploy Monitoring Stack

on:
  push:
    branches:
      - groupTest
      - main
    paths:
      - 'k8s/monitoring/**'
      - '.github/workflows/monitoring-stack.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - uses: azure/aks-set-context@v3
        with:
          resource-group: rg-group1-austriaeast
          cluster-name: grp1-aks
      
      - name: Install Helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      
      - name: Deploy Monitoring
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo update
          helm upgrade --install kube-prometheus-stack prometheus-community/kube-prometheus-stack \
            --namespace monitoring \
            --create-namespace \
            --wait \
            --values k8s/monitoring/values.yaml
      
      - name: Apply Monitoring Manifests
        run: |
          echo "Applying ServiceMonitors and PrometheusRules..."
          kubectl apply -f k8s/monitoring/backend-monitor.yaml || true
          kubectl apply -f k8s/monitoring/frontend-monitor.yaml || true
          kubectl apply -f k8s/monitoring/alerts.yaml || true
          echo "✅ Monitoring manifests applied"
      
      - name: Verify Deployment
        run: |
          echo "=== Monitoring Services ==="
          kubectl get svc -n monitoring
          echo ""
          echo "=== Monitoring Pods ==="
          kubectl get pods -n monitoring